global:
  resolve_timeout: 1m
route:
  group_by: ['Instances']  
  group_wait: 10s 
  group_interval: 10s 
  repeat_interval: 1h
  receiver: 'slack'


receivers:
  - name: 'slack'
    slack_configs:
    - channel: '#home-server'
      send_resolved: true
      api_url: 'https://hooks.slack.com/services/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'
      icon_url: https://avatars3.githubusercontent.com/u/3380462 
      title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}]
      System Issue!'
      text: >-
          <@U03739ZHE0M>
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}` {{ end }}

