version: "3"
services:
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes: 
      - /root/alertmanager/alertmanager.yml:/etc/prometheus/alertmanager.yml
      - /root/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command: --config.file=/etc/alertmanager/alertmanager.yml
    restart: unless-stopped

