version: '3.6'

services:
  # Database
  db:
    image: mysql:latest
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: {{ $password }}
      MYSQL_DATABASE: {{ $wordpress }}
      MYSQL_USER: {{ $wordpressuser }}
      MYSQL_PASSWORD: {{ $password }}
    networks:
      - wordpress
      
  # phpmyadmin / adminer to handle the administration of MySQL over the Web
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - '8080:80'
    environment:
      PMA_HOST: {{ $db }}
      MYSQL_ROOT_PASSWORD: {{ $password }}
    networks:
      - wordpress
      
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    ports:
      - '80:80'
    restart: unless-stopped
    volumes: 
      - ./html:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: {{ $wordpress }}
      WORDPRESS_DB_PASSWORD: {{ $wordpress }}
    networks:
      - wordpress
  
  # Adminer - same function as phpmyadmin (you can choose one)
  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8088:8080"
    networks:
      - wordpress
      
networks:
  wordpress:
volumes:
  db_data:
