{\rtf1\ansi\ansicpg1252\cocoartf2580
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0

\f0\fs24 \cf0 version: "3"\
services:\
  navidrome:\
    image: deluan/navidrome:latest\
    container_name: navidrome\
    restart: always\
    ports:\
      - "4533:4533"\
    environment:\
      ND_SCANSCHEDULE: 10s\
      ND_LOGLEVEL: info\
      ND_BASEURL: ""\
    volumes:\
      - "./data:/data"\
      - "./music:/music:ro"\
\
  metube:\
    image: alexta69/metube\
    container_name: metube\
    restart: unless-stopped\
    ports:\
      - "8081:8081"\
    volumes:\
      - "./music:/downloads"}