version: "3.6"
  
services:
  openproject:
    image: openproject/community:12
    container_name: openproject
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - /var/lib/openproject/pgdata:/var/openproject/pgdata
      - /var/lib/openproject/assets:/var/openproject/assets
    environment:
      - SERVER_HOSTNAME= {{ Your Domain }}
      - SECRET_KEY_BASE= {{ Your Secret }}
